### PR TITLE
Support non-image / video assets

### PR DESCRIPTION
**Pull request by frosty**
This PR adds support for non-image and video assets. It goes alongside the https://github.com/wordpress-mobile/WordPress-iOS/tree/feature/media-library-filetypes branch for WPiOS.

For assets that aren't images or videos, it adds an icon and document file extension label to the media cells:

screen shot 2017-04-26 at 15 41 21

and displays the filename in the 'caption' area at the bottom of the cell.

To test:

* The easiest way is probably to check out the [WPiOS branch](https://github.com/wordpress-mobile/WordPress-iOS/tree/feature/media-library-filetypes) that uses this PR's branch
* Ensure you have documents in a media library, and test that their icons display the new format

### CODE REVIEW

**Comment by frosty** [comment]
@SergioEstevao I pushed up some changes to address audio assets, as we discussed. Currently preview isn't supported for audio PHAssets as a) it seems like a complicated procedure, and b) it's very much an edge case having audio items in the photos library.

If you use this branch in conjunction with the updated WPiOS branch, you should now see both an updated collection view cell in the media library, and an updated preview that plays back the audio in the media item view controller:

simulator screen shot 27 apr 2017 23 40 04

**Comment by SergioEstevao** [comment]
@frosty when using the branch on the main iOS app, I can see the audio files on the media library list:

simulator screen shot 28 apr 2017 11 56 56

But when I press on them, first I see this: 
screen shot 2017-04-28 at 11 57 32

I was expecting a play Button like videos instead of the audio icon on the preview.

And when I press on the Audio icon it opens the preview but shows this:

screen shot 2017-04-28 at 11 57 39

**Comment by frosty** [comment]
@SergioEstevao As we discussed on Slack, I've updated the cells to show the file extension if it's available:

simulator screen shot 28 apr 2017 16 28 49

The other issues we can address in WPiOS.

**Comment by SergioEstevao** [comment]
:shipit:

**Comment by frosty** [comment]
Thanks @SergioEstevao!

**Pull request merged**
