### PR TITLE
Fix preview frame media sizes

### PR DESCRIPTION
**Pull request by SergioEstevao**
The asset preview was not being correctly centered on phones with no home button.

This PR updates the screen to take in account the top and bottom guidelines.

To test:
 - Start the demo app
 - Tap on +
 - Open the camera roll
 - LongPress or ForceTouch an asset to see it's preview
 - Check that image/video is centered.
 - Rotate the device and check that media is still centered.

### CODE REVIEW

**Comment by etoledom** [comment]
Hey @SergioEstevao 

I've been testing and comparing with develop, and I don't really see any difference 🤔 
Is there a special size/aspect-ratio of images/videos that makes this issue show up?

**Comment by SergioEstevao** [comment]
@etoledom did you test on iPhone X kind of phone? I think the main thing here is to take in account the bottom space used by the home indicator.

**Comment by frosty** [comment]
I just tested this on the XR, and the image appears to not be centered in the black space – there's more space below than above. It _is_ centered in the entire screen space though (if you measure from the very top of the screen to the very bottom, including the navigation bar). Is that expected?

**Comment by SergioEstevao** [comment]
@etoledom and @frosty I updated the code, it should now be centered in the center of the available (black) screen.

**Pull request merged**
